name: toastr
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: https://www.example.com
# author: Jermaine Oppong <email@example.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  angular: ^5.3.1
  angular_components: ^0.13.0

dev_dependencies:
  angular_test: ^2.2.0
  build_runner: ^1.5.2
  build_test: ^0.10.8
  build_web_compilers: ^2.1.1
  pedantic: ^1.0.0
  test: ^1.5.1
